baseURL = 'https://nostedime.github.io/'
languageCode = 'en-us'
title = 'My CS adventure and more'
[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"
[caches]
  [caches.images]
    dir = ':cacheDir/images'
